services:
  cups:
    container_name: cups
    build: .
    restart: always
    network_mode: host
    environment:
      CUPSADMIN: cups
      CUPSPASSWORD: cups
      RUNLEVEL: 1
    ports:
      - 631:631
    volumes:
      - ./services:/services
      - ./config:/config
