services:
  cups:
    container_name: cups
    build: .
    restart: always
    network_mode: host
    platform: linux/amd64
    environment:
      PRINTER_ID: Brother_720
      CUPSADMIN: cups
      CUPSPASSWORD: cups
      RUNLEVEL: 1
      DEBIAN_FRONTEND: noninteractive
      OUTPUT_SUBPATH: vprint
    ports:
      - 631:631
    volumes:
      - ./services:/services
      - ./config:/config
      - /tmp/output:/mnt/output
